language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
# command to install dependencies
before_install:
  - pip install -e .

# command to run tests
script:
  - nosetests
